import os


STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = ""
STRIPE_PUBLISHABLE_KEY = ""

CURRENCY = "usd"
CURRENCY_DECIMALS = 2
MIN_DONATION = 1.0
MAX_DONATION = 10000.0

DISABLE_3DS = True

PROXY_HOST = ""
PROXY_PORT = ""
PROXY_USERNAME = ""
PROXY_PASSWORD = ""
PROXY_SCHEME = "https"  # "https" or "http"

STRIPE_MAX_NETWORK_RETRIES = 2
STRIPE_TIMEOUT_SECONDS = 20
