# Replace these with your actual Stripe keys
STRIPE_SECRET_KEY = "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"
STRIPE_PUBLISHABLE_KEY = "pk_live_51QUkrvFvHqA3X646lP6MtXjQ9mjpklXXLajOsibdYvOgYTEwapLOEeUSZ2wcuobOdkeh9Z0rfNrAy7JizWhSiPez00NLp7OiBS"

CURRENCY = "usd"
CURRENCY_DECIMALS = 2
MIN_DONATION = 1.0
MAX_DONATION = 10000.0

DISABLE_3DS = True

PROXY_HOST = ""
PROXY_PORT = ""
PROXY_USERNAME = ""
PROXY_PASSWORD = ""
PROXY_SCHEME = "https"  # "https" or "http"

STRIPE_MAX_NETWORK_RETRIES = 2
STRIPE_TIMEOUT_SECONDS = 20
